/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Panel.DGPanel;

import Contantes.DGPanelConstantes;
import SQLUtil.ComponetsDb;
import Util.Utilidades;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Cristian
 */
public class DGPanel extends javax.swing.JPanel {

    private String nmTabela;
    private boolean isGridMode;
    private boolean isDesignLoaded;
    private boolean isGridLoaded;
    private ArrayList<DBPanelAtributo> atributos = new ArrayList<DBPanelAtributo>();

    /**
     * Creates new form DGPanel
     */
    public DGPanel() {
        initComponents();
        init();

    }

    public void init() {
        setViewMode(DGPanelConstantes.GRIDMODE);
        dGGridPanel1.getGrid().getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                montaPanelDesign(dGGridPanel1.getGrid().getSelectedRow());
                System.out.println(dGGridPanel1.getGrid().getSelectedRow());
            }
        });
    }

    public void loadPanel() {
        for (HashMap hm : ComponetsDb.getAtributosColumns(nmTabela)) {
            DBPanelAtributo dbPanelAtributo = new DBPanelAtributo();
            dbPanelAtributo.setNmAtributo(Utilidades.validaString(hm.get("NM_ATRIBUTO")));
            dbPanelAtributo.setPosX(Utilidades.validaInt(hm.get("POS_X")));
            dbPanelAtributo.setPosY(Utilidades.validaInt(hm.get("POS_Y")));
            dbPanelAtributo.setLarguraGrid(Utilidades.validaInt(hm.get("LARGURA_GRID")));
            dbPanelAtributo.setLarguraDesign(Utilidades.validaInt(hm.get("LARGURA_DESIGN")));
            dbPanelAtributo.setAlturaDesign(Utilidades.validaInt(hm.get("ALTURA_DESIGN")));
            dbPanelAtributo.setTipoComponente(Utilidades.validaString(hm.get("TIPO_COMPONENTE")));
            dbPanelAtributo.setDsAtributo(Utilidades.validaString(hm.get("DS_ATRIBUTO")));
            atributos.add(dbPanelAtributo);
        }
    }

    public void changeViewMode() {
        if (isGridMode) {
            setViewMode(DGPanelConstantes.DESIGNMODE);
        } else {
            setViewMode(DGPanelConstantes.GRIDMODE);
        }
    }

    public void setViewMode(DGPanelConstantes view) {
        if (view.equals(DGPanelConstantes.GRIDMODE)) {
            if (!isGridLoaded && atributos.size() > 0) {
                dGGridPanel1.setAtributos(atributos, nmTabela);
                isGridLoaded = true;
            }
            ((CardLayout) (panelControlador.getLayout())).show(panelControlador, "GridMode");
            System.out.println("GridMode");
            isGridMode = true;
        } else if (view.equals(DGPanelConstantes.DESIGNMODE)) {
            ((CardLayout) (panelControlador.getLayout())).show(panelControlador, "designMode");
            montaPanelDesign();
            System.out.println("designMode");
            isGridMode = false;
        }
    }

    public void montaPanelDesign(int line) {
        dBDesignPanel1.setAtributos(atributos, null, line);
    }

    public void montaPanelDesign() {
        dBDesignPanel1.setAtributos(atributos, null, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCPanel1 = new ComponentesVisuais.JCPanel();
        panelControlador = new javax.swing.JPanel();
        dBDesignPanel1 = new Swing.Panel.DGPanel.DBDesignPanel();
        dGGridPanel1 = new Swing.Panel.DGPanel.DGGridPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonPadrao1 = new Botões.JButtonPadrao();

        setLayout(new java.awt.BorderLayout());

        jCPanel1.setLayout(new java.awt.BorderLayout());

        panelControlador.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout dBDesignPanel1Layout = new javax.swing.GroupLayout(dBDesignPanel1);
        dBDesignPanel1.setLayout(dBDesignPanel1Layout);
        dBDesignPanel1Layout.setHorizontalGroup(
            dBDesignPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        dBDesignPanel1Layout.setVerticalGroup(
            dBDesignPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        panelControlador.add(dBDesignPanel1, "designMode");
        panelControlador.add(dGGridPanel1, "GridMode");

        jCPanel1.add(panelControlador, java.awt.BorderLayout.CENTER);

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jButtonPadrao1.setText("Detalhe/Form");
        jButtonPadrao1.setFocusable(false);
        jButtonPadrao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPadrao1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPadrao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeJBActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonPadrao1);

        jCPanel1.add(jToolBar1, java.awt.BorderLayout.EAST);

        add(jCPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void changeJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeJBActionPerformed
        changeViewMode();
    }//GEN-LAST:event_changeJBActionPerformed

    /**
     * Get the value of nmTabela
     *
     * @return the value of nmTabela
     */
    public String getNmTabela() {
        return nmTabela;
    }

    /**
     * Set the value of nmTabela
     *
     * @param nmTabela new value of nmTabela
     */
    public void setNmTabela(String nmTabela) {
        this.nmTabela = nmTabela;
        loadPanel();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Panel.DGPanel.DBDesignPanel dBDesignPanel1;
    private Swing.Panel.DGPanel.DGGridPanel dGGridPanel1;
    private Botões.JButtonPadrao jButtonPadrao1;
    private ComponentesVisuais.JCPanel jCPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelControlador;
    // End of variables declaration//GEN-END:variables
}
