/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing.Panel.DGPanel;

import Contantes.DGPanelConstantes;
import java.awt.CardLayout;

/**
 *
 * @author Cristian
 */
public class DGPanel extends javax.swing.JPanel {

    private boolean isGridMode;

    /**
     * Creates new form DGPanel
     */
    public DGPanel() {
        initComponents();
    }

    public void init() {
        setViewMode(DGPanelConstantes.GRIDMODE);
    }

    public void changeViewMode() {
        if (isGridMode) {
            setViewMode(DGPanelConstantes.DESIGNMODE);
        } else {
            setViewMode(DGPanelConstantes.GRIDMODE);
        }
    }

    public void setViewMode(DGPanelConstantes view) {
        if (view.equals(DGPanelConstantes.GRIDMODE)) {
            ((CardLayout) (panelControlador.getLayout())).show(panelControlador, "GridMode");
            isGridMode = true;
        } else if (view.equals(DGPanelConstantes.DESIGNMODE)) {
            ((CardLayout) (panelControlador.getLayout())).show(panelControlador, "designMode");
            isGridMode = false;
        }
    }
    
    public void montaPanelDesign(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelControlador = new javax.swing.JPanel();
        gridSP = new javax.swing.JScrollPane();
        gridTable = new javax.swing.JTable();
        designView = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelControlador.setLayout(new java.awt.CardLayout());

        gridTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridSP.setViewportView(gridTable);

        panelControlador.add(gridSP, "GridMode");

        javax.swing.GroupLayout designViewLayout = new javax.swing.GroupLayout(designView);
        designView.setLayout(designViewLayout);
        designViewLayout.setHorizontalGroup(
            designViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        designViewLayout.setVerticalGroup(
            designViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panelControlador.add(designView, "designMode");

        add(panelControlador, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        changeViewMode();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel designView;
    private javax.swing.JScrollPane gridSP;
    private javax.swing.JTable gridTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelControlador;
    // End of variables declaration//GEN-END:variables
}
